---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
  # This is the module name
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
  # This is the module name
    dnf: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"