---

- hosts: all
  become: true
  tasks:

  - name: update repository index
  # This is the module name
    apt: 
      update_cache: yes

  - name: install apache2 package
  # This is the module name
    apt: 
      name: apache2
      state: latest

  - name: add php support for apache
  # This is the module name
    apt: 
      name: libapache2-mod-php
      state: latest