- name: install mariadb package (CentOS)
  tags: db_server
  dnf:
    name: mariadb
    state: latest 
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu)
  tags: db_server
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"